# cellarium.http.conf.ServerConfig

selfPort: 8080
selfUrl: http://127.0.0.1:8080
cluster:
  - url: http://127.0.0.1:8080
    replicas: 
      
requestHandlerThreadCount: 6
closeSessions: true
virtualNodeAmount: 10
maxTasksPerNode: 1

acceptors:
  - port: 8080
    reusePort: true