# cellarium.http.conf.ServerConfig

selfPort: 8080
selfUrl: http://localhost:8080
clusterUrls:
  - http://localhost:8080
localThreadAmount: 6
remoteThreadAmount: 6
closeSessions: true
virtualNodeAmount: 10

acceptors:
  - port: 8080
    reusePort: true